[pr_reviewer]
extra_instructions = """
レビュー結果は日本語で出力してください．  
以下の観点で丁寧に確認し，**「なぜその指摘が必要か」まで含めた具体的な改善案**を記述してください．

🔒 セキュリティリスク（Security）
- 情報漏洩，認証周りの不備，依存ライブラリの脆弱性など

⚡️ パフォーマンス（Performance）
- 無駄なループ，重い処理，リソース競合の可能性

🧹 コーディング規約・構文（Code Style）
- 命名規則・インデント・構文ミスなど，プロジェクトのガイドラインに準拠しているか

📖 可読性と保守性（Readability / Maintainability）
- 関数やクラスの責務が明確か，コメントが適切か，将来的に読みやすいコードかどうか

出力は以下の形式にしてください：

【指摘カテゴリ】：⚠️ パフォーマンス  
【対象コード】：Line XX - `useEffect(() => {...}, [])`  
【指摘内容】：初期描画時にfetchが二重に走る可能性があります．依存配列に明示的に変数を指定することで回避できます．

読み手が納得できる理由付けと共に，**指摘というより「伴走するアドバイス」のようなトーン**で記述してください．
"""

[pr_description]
extra_instructions = """
プルリクエストのタイトルと説明文は日本語で出力してください．  
以下のフォーマットを守り，**読み手が「何を」「なぜ」やったのかを一目で把握できるように**記述してください．

---

### 🚀 タイトル（Title）  
50文字以内で端的に変更の内容を表現してください（例：「カメラ接続失敗時のログ改善」）．

### ✏️ 概要（Summary）  
このPRの目的と背景を簡潔に説明してください．「なぜこの変更が必要か」を中心に書いてください．

### 🔧 主な変更点（Main Changes）  
- 実施した具体的な変更内容（例：Slack通知の改善，linterエラー修正 など）
- 影響範囲（どの画面・機能に影響するか）
- 想定される副作用（あれば）

---

必要に応じて「Issue番号」や「関連するチケット」なども記載してください（例：Closes #123）．
"""

[pr_code_suggestions]
extra_instructions = """
コードの改善提案は日本語で記述してください．  
以下の観点を踏まえ，**「どう変えるべきか」だけでなく「なぜ変えるべきか」も明確に**書いてください：

- 保守性向上（責務の明確化・重複削減・再利用性）
- パフォーマンス向上（処理の軽量化・遅延読み込みなど）
- セキュリティ（安全な書き方への修正）
- コーディングスタイル統一（命名・改行・構文など）

出力形式：

【変更前の問題点】  
このコードはXのような処理を行っていますが，Yの理由で可読性／性能に課題があります．

【改善案とその理由】  
代替案として以下のような書き方ができます：  
```ts
// 具体的な改善コード

このようにすることで，Zというメリットがあります．
冗長な説明ではなく，「実装者がすぐに着手しやすいように」実用的かつ親切な解説を意識してください．
"""

[pr_update_changelog]
extra_instructions = """
以下のフォーマットに従って，日本語でCHANGELOGエントリーを生成してください．  
各項目は **絵文字＋カテゴリ名＋英語カテゴリ名（括弧付き）** をセットで見出しとし，その下に対応する変更点をリスト形式で記述してください．

### 形式例：

🚸 ユーザー向けの変更 (User Facing Changes)
- [変更内容]

✨ 新機能 (New Features)
- [新機能の内容]

🛠 機能改善 (Improvements)
- [改善点の内容]

🐛 バグ修正 (Bug Fixes)
- [修正内容と背景]

🧰 非機能改善 (DevOps Improvements)
- [開発体験・CI/CD・環境変数などの改善]

⚠️ 既知の不具合 (Known Issues)
- [既知の不具合とその状況]

### 補足ルール：
- 文章は「〜しました」「〜されるようになりました」のように，柔らかい日本語で簡潔に書いてください．
- カテゴリがない場合はスキップして構いません．
- 対象ファイルや機能が特定できる場合は括弧などで補足してください（例：`auth/register.ts`）．
"""

[github_action_config]
auto_review = true
auto_describe = true
