name: PR-Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created, edited]

jobs:
  # stagingブランチからmasterブランチへのPRの場合の自動実行
  pr_agent_auto_job:
    if: github.event.sender.type != 'Bot' && github.base_ref == 'main' && github.head_ref == 'develop'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent (Auto)
        id: pr-agent-auto
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action_config.auto_review: "false"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "false"
          PR_AGENT.COMMAND: "/update_changelog"
