name: PR-Agent (Manual for staging-to-master)

on:
  issue_comment:
    types: [created]

jobs:
  pr_agent_manual_command:
    if: github.event.sender.type != 'Bot'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Get PR Info
        id: pr_info
        uses: juliangruber/get-pull-request-info-action@v1
        with:
          pull-request-number: ${{ github.event.issue.number }}

      - name: Run PR-Agent on Manual Command
        id: pr-agent
        if: steps.pr_info.outputs.base-ref-name == 'main' && steps.pr_info.outputs.head-ref-name == 'develop'
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action_config.auto_review: "false"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "false"
