name: PR-Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - main
  issue_comment:
    types: [created, edited]

jobs:
  pr_agent_manual_job:
    if: github.event.sender.type != 'Bot' && github.event_name == 'issue_comment' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent (Manual)
        id: pr-agent-manual
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action_config.auto_review: "false"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "false"


