name: PR-Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created, edited]

jobs:
  pr_agent_job:
    # ボットからのイベントは除外する
    if: github.event.sender.type != 'Bot'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent
        id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          # 上記で設定したシークレット名を指定
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # tomlファイルによる設定を有効化
          CONFIG_FILE: .pr_agent.toml
